version: '3.1'

services:
  redis:
    image: redis
    container_name: redis-xylem
    ports:
      - 6379:6379
  db:
    image: kartoza/postgis:13.0
    command: postgres -c 'max_connections=200'
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: xylem
    ports:
      - 5432:5432
